services:
  mongodb:
    image: mongo:7.0
    container_name: kanban-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: kanban
    networks:
      - kanban-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kanban-backend
    restart: unless-stopped
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/kanban
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - kanban-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kanban-frontend
    restart: unless-stopped
    ports:
      - "5173:3000"
    networks:
      - kanban-network

volumes:
  mongodb_data:
    driver: local

networks:
  kanban-network:
    driver: bridge
